# Generated by Django 2.0.6 on 2018-12-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name', '-exam_grade']},
        ),
    ]
