# Generated by Django 2.0.6 on 2018-12-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20181216_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
